import type { Metadata } from "next";
import { Chocolate_Classical_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Chocolate_Classical_Sans({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased capitalize overflow-y-scroll `}
      >
        <SessionProvider session={session} key={session?.user?.id}>
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
